
export class propData {
    constructor(
        public _id: String,
        public DeveloperName: String,
        public DeveloperBriefDetails: String,
        public DeveloperLogo: String,
        public ProjectName: String,
        public aboutProperty: String,
        public    MuncipleCorporationName: String,  
        public    locationName: String,
        public    connectivitytoProject: String,
        public    basicNecessity: String,
        public    landParcelInAcres: String,
        public    constructionType:String,
        public    possessionTimeline: String,
        public    totalNumberOfUnits:Number,
        public    Typology: String,
        public    noOfTowers: Number,
        public    highriseCount: String,
        public    Flat_Floor: String,
        public    carpetArea: String,
        public    minPricing: String,
        public    maxPricing: String,
        public    Lobby: String,
        public    Living:String,
        public    Dining: String,
        public    LivTerrace_Balcony: String,
        public    Kitchen: String,
        public    DryBalcony:String,
        public    CommonW_c: String,
        public    MasterBedroom: String,
        public    M_B_W_c: String,
        public    Terrace_Balcony: String,
        public    GuestBedroom: String,
        public    G_B_W_c: String,          
        public    Garden:String,  
        public    KidsPlay:String,
        public    gym: String,
        public    ClubHouse: String,
        public    SwimmingPool: String,
        public    JoggingTrack: String,            
        public    AmphiTheatre:String,            
        public    CoWorkSpace: String,           
        public    SeniorCitizenSitout:String,            
        public    Football_Cricket:String,            
        public    Badminton_Squash:String,            
        public    ECharging: String,            
        public    others: String,            
        public    CommercialsinProject:String,            
        public    GasConnection: String,            
        public    WaterProvision:String,            
        public    STP: String,            
        public    EarthquakeResistance: String,            
        public    WaterHarvesting: String,            
        public    DGBackup: String,            
       public   rating: number,
        public    lattitude:String,
        public    longitude:String,
        public    youtubeUri:String,
        public    imagesUri:any[],
        public dimensionMapImages:any[]        
    ) {}
  }